// Base de segurança do Mapa de Lojas — os 45 stands do mapa standalone
// (Mapa_Stands_Vendas, outubro/2026), copiados como estavam.
//
// A fonte VIVA é a planilha (ver PLANILHA_LOJAS em lojas.ts). Esta lista existe
// por dois motivos:
//  1) o mapa abre na hora, sem esperar o Google — e continua de pé se a
//     planilha cair;
//  2) linha da planilha sem latitude/longitude herda daqui a posição do mesmo
//     endereço (mesma regra do HTML), em vez de sumir do mapa.
//
// As coordenadas são ESTIMADAS (3 casas, ~100 m): o pino nasce "aproximado" e
// o navegador refina pelo endereço (usePosicoesRefinadas). Para mudar um stand,
// mude a planilha — editar aqui só altera o fallback.

import type { LojaSemente } from "@/lib/lojas/lojas";

export const LOJAS_SEMENTE: readonly LojaSemente[] = [
  {
    construtora: "Cavazani",
    nome: "Complexo Precioso (Guarulhos)",
    endereco: "Rua Faustino Ramalho, 704",
    bairro: "Jd. Vila Galvão, Guarulhos",
    zona: "Grande SP",
    lat: -23.452,
    lng: -46.533,
  },
  {
    construtora: "Cavazani",
    nome: "Lapa",
    endereco: "Av. Ermano Marchetti, 381",
    bairro: "Lapa",
    zona: "Zona Oeste",
    lat: -23.5265,
    lng: -46.6985,
  },
  {
    construtora: "Cavazani",
    nome: "Urbano First (Shopping Aricanduva)",
    endereco: "Av. Aricanduva, 5555 – Shopping Aricanduva, ao lado da loja TIM",
    bairro: "Aricanduva",
    zona: "Zona Leste",
    lat: -23.566,
    lng: -46.505,
  },
  {
    construtora: "Vitta Residencial",
    nome: "Vila Prudente",
    endereco: "Av. Paes de Barros, 3695",
    bairro: "Vila Prudente",
    zona: "Zona Leste",
    lat: -23.574,
    lng: -46.583,
  },
  {
    construtora: "Vitta Residencial",
    nome: "Vila Andrade",
    endereco: "Rua Nelson Gama, 439",
    bairro: "Vila Andrade",
    zona: "Zona Sul",
    lat: -23.618,
    lng: -46.74,
  },
  {
    construtora: "Vitta Residencial",
    nome: "Freguesia",
    endereco: "Rua Bonifácio Cubas, 159",
    bairro: "Freguesia do Ó",
    zona: "Zona Norte",
    lat: -23.49,
    lng: -46.693,
  },
  {
    construtora: "Cury",
    nome: "Cambuci",
    endereco: "Rua Clímaco Barbosa, 750",
    bairro: "Cambuci",
    zona: "Centro",
    lat: -23.57,
    lng: -46.624,
  },
  {
    construtora: "Cury",
    nome: "Vila Formosa",
    endereco: "Avenida Guilherme Giorgi, 1041",
    bairro: "Vila Formosa",
    zona: "Zona Leste",
    lat: -23.547,
    lng: -46.558,
  },
  {
    construtora: "Cury",
    nome: "Vila Guilherme",
    endereco: "Rua José Bernardo Pinto, 1400",
    bairro: "Vila Guilherme",
    zona: "Zona Norte",
    lat: -23.511,
    lng: -46.605,
  },
  {
    construtora: "Cury",
    nome: "Vila Anastácio",
    endereco: "Avenida do Anastácio, 740",
    bairro: "Vila Anastácio",
    zona: "Zona Oeste",
    lat: -23.52,
    lng: -46.733,
  },
  {
    construtora: "Cury",
    nome: "Freguesia / Limão",
    endereco: "Avenida Otaviano Alves de Lima, 3600",
    bairro: "Freguesia do Ó",
    zona: "Zona Norte",
    lat: -23.503,
    lng: -46.683,
  },
  {
    construtora: "Cury",
    nome: "Água Branca",
    endereco: "Av. Ermano Marchetti, 1009",
    bairro: "Lapa",
    zona: "Zona Oeste",
    lat: -23.525,
    lng: -46.693,
  },
  {
    construtora: "Cury",
    nome: "Vila Leopoldina",
    endereco: "Rua Othão, 15",
    bairro: "Vila Leopoldina",
    zona: "Zona Oeste",
    lat: -23.528,
    lng: -46.724,
  },
  {
    construtora: "Cury",
    nome: "Jaguaré",
    endereco: "Avenida Jaguaré, 1487",
    bairro: "Jaguaré",
    zona: "Zona Oeste",
    lat: -23.543,
    lng: -46.75,
  },
  {
    construtora: "Cury",
    nome: "Santo Amaro",
    endereco: "R. João Alfredo, 593",
    bairro: "Santo Amaro",
    zona: "Zona Sul",
    lat: -23.654,
    lng: -46.71,
  },
  {
    construtora: "Cury",
    nome: "Parque Guarapiranga",
    endereco: "Avenida Rio Bonito, 41",
    bairro: "Parque Guarapiranga",
    zona: "Zona Sul",
    lat: -23.677,
    lng: -46.714,
  },
  {
    construtora: "Emccamp",
    nome: "Sinfonia Santo Amaro",
    endereco: "Av. Arquiteto Carlos Bratke, 979",
    bairro: "Jd. Caravelas",
    zona: "Zona Sul",
    lat: -23.658,
    lng: -46.722,
  },
  {
    construtora: "Emccamp",
    nome: "MOB Campo Limpo",
    endereco: "Estrada de Itapecerica, 3585",
    bairro: "Campo Limpo",
    zona: "Zona Sul",
    lat: -23.633,
    lng: -46.77,
  },
  {
    construtora: "Emccamp",
    nome: "Atlas Sacomã",
    endereco: "Av. Nossa Sra. da Encarnação, 374",
    bairro: "Sacomã",
    zona: "Zona Sul",
    lat: -23.605,
    lng: -46.601,
  },
  {
    construtora: "Emccamp",
    nome: "Line Praça da Árvore",
    endereco: "Av. Jabaquara, 435",
    bairro: "Praça da Árvore",
    zona: "Zona Sul",
    lat: -23.597,
    lng: -46.64,
  },
  {
    construtora: "Emccamp",
    nome: "Origem Itaquera",
    endereco: "Estr. do Pêssego, 157",
    bairro: "Itaquera",
    zona: "Zona Leste",
    lat: -23.568,
    lng: -46.48,
  },
  {
    construtora: "Emccamp",
    nome: "Serena Residence",
    endereco: "Av. Dr. Assis Ribeiro, 3480",
    bairro: "Ermelino Matarazzo",
    zona: "Zona Leste",
    lat: -23.519,
    lng: -46.5,
  },
  {
    construtora: "Emccamp",
    nome: "Vision Penha",
    endereco: "Av. Amador Bueno da Veiga, 1127",
    bairro: "Penha",
    zona: "Zona Leste",
    lat: -23.527,
    lng: -46.53,
  },
  {
    construtora: "Emccamp",
    nome: "Altus Vila Prudente",
    endereco: "Avenida Professor Luiz Ignácio Anhaia Mello, 1860",
    bairro: "Vila Prudente",
    zona: "Zona Leste",
    lat: -23.587,
    lng: -46.578,
  },
  {
    construtora: "Emccamp",
    nome: "Line Parada Inglesa",
    endereco: "R. Domingos Calheiros, 132",
    bairro: "Parada Inglesa",
    zona: "Zona Norte",
    lat: -23.478,
    lng: -46.611,
  },
  {
    construtora: "Emccamp",
    nome: "Icônico Jaraguá",
    endereco: "Estrada das Taipas, 745",
    bairro: "Jaraguá",
    zona: "Zona Norte",
    lat: -23.461,
    lng: -46.724,
  },
  {
    construtora: "Emccamp",
    nome: "MOB Barra Funda",
    endereco: "Rua Quirino dos Santos, 102",
    bairro: "Barra Funda",
    zona: "Zona Oeste",
    lat: -23.529,
    lng: -46.664,
  },
  {
    construtora: "Econ",
    nome: "Vila Moraes",
    endereco: "Av. Cursino, 5000",
    bairro: "Vila Moraes",
    zona: "Zona Sul",
    lat: -23.628,
    lng: -46.615,
  },
  {
    construtora: "Econ",
    nome: "Jurubatuba",
    endereco: "Rua Taguapacá, 261",
    bairro: "Jurubatuba",
    zona: "Zona Sul",
    lat: -23.68,
    lng: -46.696,
  },
  {
    construtora: "Econ",
    nome: "Vila Emir",
    endereco: "Av. Nossa Senhora do Sabará, 4885",
    bairro: "Vila Emir",
    zona: "Zona Sul",
    lat: -23.69,
    lng: -46.67,
  },
  {
    construtora: "Econ",
    nome: "Interlagos",
    endereco: "Rua Antônio Le Voci, 345",
    bairro: "Terceira Divisão de Interlagos",
    zona: "Zona Sul",
    lat: -23.7,
    lng: -46.69,
  },
  {
    construtora: "Direcional Engenharia",
    nome: "Barra Funda",
    endereco: "Av. Francisco Matarazzo, 486",
    bairro: "Barra Funda",
    zona: "Zona Oeste",
    lat: -23.528,
    lng: -46.664,
  },
  {
    construtora: "Direcional Engenharia",
    nome: "Ipiranga",
    endereco: "Rua Eliseo de Castro, 165",
    bairro: "Ipiranga",
    zona: "Zona Sul",
    lat: -23.59,
    lng: -46.605,
  },
  {
    construtora: "Direcional Engenharia",
    nome: "Butantã",
    endereco: "Rua Alvarenga, 1203",
    bairro: "Butantã",
    zona: "Zona Oeste",
    lat: -23.569,
    lng: -46.709,
  },
  {
    construtora: "Riva",
    nome: "Santo Amaro",
    endereco: "Rua João Dias, 1243",
    bairro: "Santo Amaro",
    zona: "Zona Sul",
    lat: -23.646,
    lng: -46.724,
  },
  {
    construtora: "Riva",
    nome: "Vila Anastácio",
    endereco: "Rua Fortunato Ferraz, 1141",
    bairro: "Vila Anastácio",
    zona: "Zona Oeste",
    lat: -23.523,
    lng: -46.73,
  },
  {
    construtora: "Longitude Incorporadora",
    nome: "Perus",
    endereco: "Rua Antônio Maia, 805",
    bairro: "Perus",
    zona: "Zona Norte",
    lat: -23.4,
    lng: -46.755,
    obs: "Sem decorado, somente atendimento",
  },
  {
    construtora: "Longitude Incorporadora",
    nome: "Itaquera",
    endereco: "Rua Dr. Aureliano Barreiros, 180",
    bairro: "Itaquera",
    zona: "Zona Leste",
    lat: -23.54,
    lng: -46.457,
    obs: "Decorado de 2 dorm e 1 dorm office",
  },
  {
    construtora: "Longitude Incorporadora",
    nome: "Centro",
    endereco: "Rua São Bento, 385",
    bairro: "Centro",
    zona: "Centro",
    lat: -23.5465,
    lng: -46.635,
    obs: "Decorado de 1 dorm office e studio de 24 m²",
  },
  {
    construtora: "Mundo Apto",
    nome: "Av. Santo Amaro",
    endereco: "Av. Santo Amaro, 5236",
    bairro: "Brooklin",
    zona: "Zona Sul",
    lat: -23.614,
    lng: -46.687,
  },
  {
    construtora: "Trisul",
    nome: "Elev Saúde",
    endereco: "Av. Miguel Estefano, 72",
    bairro: "Saúde",
    zona: "Zona Sul",
    lat: -23.613,
    lng: -46.637,
  },
  {
    construtora: "Trisul",
    nome: "Elev Ipiranga",
    endereco: "Rua Eduardo Carlos Pereira, 430",
    bairro: "Ipiranga",
    zona: "Zona Sul",
    lat: -23.593,
    lng: -46.612,
  },
  {
    construtora: "Trisul",
    nome: "Elev Vila Prudente",
    endereco: "Av. Vila Ema, 1730",
    bairro: "Vila Prudente",
    zona: "Zona Leste",
    lat: -23.589,
    lng: -46.574,
  },
  {
    construtora: "Trisul",
    nome: "Elev Sacomã",
    endereco: "Rua Malvina Ferrara Samarone, 270",
    bairro: "Sacomã",
    zona: "Zona Sul",
    lat: -23.609,
    lng: -46.609,
  },
  {
    construtora: "Trisul",
    nome: "Elev Butantã",
    endereco: "Av. Vital Brasil, 329",
    bairro: "Butantã",
    zona: "Zona Oeste",
    lat: -23.566,
    lng: -46.716,
  },
];
