/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedRadarRouteImport } from './routes/_authenticated/radar'
import { Route as AuthenticatedPainelGestorRouteImport } from './routes/_authenticated/painel-gestor'
import { Route as AuthenticatedMeuPerfilRouteImport } from './routes/_authenticated/meu-perfil'
import { Route as AuthenticatedMeuPainelRouteImport } from './routes/_authenticated/meu-painel'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedMatchRouteImport } from './routes/_authenticated/match'
import { Route as AuthenticatedLixeiraRouteImport } from './routes/_authenticated/lixeira'
import { Route as AuthenticatedLinksUteisRouteImport } from './routes/_authenticated/links-uteis'
import { Route as AuthenticatedLeadsPorCorretorRouteImport } from './routes/_authenticated/leads-por-corretor'
import { Route as AuthenticatedLeadsLandingRouteImport } from './routes/_authenticated/leads-landing'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedHojeRouteImport } from './routes/_authenticated/hoje'
import { Route as AuthenticatedEquipesRouteImport } from './routes/_authenticated/equipes'
import { Route as AuthenticatedDuplicatasRouteImport } from './routes/_authenticated/duplicatas'
import { Route as AuthenticatedDistribuicaoRouteImport } from './routes/_authenticated/distribuicao'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCorretoresRouteImport } from './routes/_authenticated/corretores'
import { Route as AuthenticatedCopaRouteImport } from './routes/_authenticated/copa'
import { Route as AuthenticatedConquistasRouteImport } from './routes/_authenticated/conquistas'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedComissoesRouteImport } from './routes/_authenticated/comissoes'
import { Route as AuthenticatedBlitzRouteImport } from './routes/_authenticated/blitz'
import { Route as AuthenticatedAgendamentosRouteImport } from './routes/_authenticated/agendamentos'
import { Route as AuthenticatedProjetosIndexRouteImport } from './routes/_authenticated/projetos.index'
import { Route as AuthenticatedOfertaAtivaIndexRouteImport } from './routes/_authenticated/oferta-ativa.index'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads.index'
import { Route as ApiPublicMetricasRouteImport } from './routes/api/public/metricas'
import { Route as AuthenticatedProjetosProjetoIdRouteImport } from './routes/_authenticated/projetos.$projetoId'
import { Route as AuthenticatedOfertaAtivaNovaRouteImport } from './routes/_authenticated/oferta-ativa.nova'
import { Route as AuthenticatedOfertaAtivaOfertaIdRouteImport } from './routes/_authenticated/oferta-ativa.$ofertaId'
import { Route as AuthenticatedLeadsLeadIdRouteImport } from './routes/_authenticated/leads.$leadId'
import { Route as ApiPublicVendasIndexRouteImport } from './routes/api/public/vendas/index'
import { Route as ApiPublicProjetosIndexRouteImport } from './routes/api/public/projetos/index'
import { Route as ApiPublicLeadsIndexRouteImport } from './routes/api/public/leads/index'
import { Route as ApiPublicCorretoresIndexRouteImport } from './routes/api/public/corretores/index'
import { Route as ApiPublicComissoesIndexRouteImport } from './routes/api/public/comissoes/index'
import { Route as ApiPublicWebhooksLandingRouteImport } from './routes/api/public/webhooks/landing'
import { Route as ApiPublicLeadsIdRouteImport } from './routes/api/public/leads/$id'
import { Route as ApiPublicHooksPushDispatchRouteImport } from './routes/api/public/hooks/push-dispatch'
import { Route as ApiPublicHooksCopilotoHandoffRouteImport } from './routes/api/public/hooks/copiloto-handoff'
import { Route as ApiPublicCorretoresIdRouteImport } from './routes/api/public/corretores/$id'
import { Route as ApiGoogleOauthCallbackRouteImport } from './routes/api/google/oauth.callback'
import { Route as ApiPublicWebhooksLeadTokenRouteImport } from './routes/api/public/webhooks/lead/$token'
import { Route as ApiPublicLeadsIdPerdaRouteImport } from './routes/api/public/leads/$id.perda'
import { Route as ApiPublicLeadsIdEventosRouteImport } from './routes/api/public/leads/$id.eventos'
import { Route as ApiPublicLeadsIdCorretorRouteImport } from './routes/api/public/leads/$id.corretor'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRadarRoute = AuthenticatedRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelGestorRoute =
  AuthenticatedPainelGestorRouteImport.update({
    id: '/painel-gestor',
    path: '/painel-gestor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeuPerfilRoute = AuthenticatedMeuPerfilRouteImport.update({
  id: '/meu-perfil',
  path: '/meu-perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeuPainelRoute = AuthenticatedMeuPainelRouteImport.update({
  id: '/meu-painel',
  path: '/meu-painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchRoute = AuthenticatedMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLixeiraRoute = AuthenticatedLixeiraRouteImport.update({
  id: '/lixeira',
  path: '/lixeira',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinksUteisRoute = AuthenticatedLinksUteisRouteImport.update({
  id: '/links-uteis',
  path: '/links-uteis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsPorCorretorRoute =
  AuthenticatedLeadsPorCorretorRouteImport.update({
    id: '/leads-por-corretor',
    path: '/leads-por-corretor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadsLandingRoute =
  AuthenticatedLeadsLandingRouteImport.update({
    id: '/leads-landing',
    path: '/leads-landing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHojeRoute = AuthenticatedHojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipesRoute = AuthenticatedEquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDuplicatasRoute = AuthenticatedDuplicatasRouteImport.update({
  id: '/duplicatas',
  path: '/duplicatas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDistribuicaoRoute =
  AuthenticatedDistribuicaoRouteImport.update({
    id: '/distribuicao',
    path: '/distribuicao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCorretoresRoute = AuthenticatedCorretoresRouteImport.update({
  id: '/corretores',
  path: '/corretores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCopaRoute = AuthenticatedCopaRouteImport.update({
  id: '/copa',
  path: '/copa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConquistasRoute = AuthenticatedConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComissoesRoute = AuthenticatedComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBlitzRoute = AuthenticatedBlitzRouteImport.update({
  id: '/blitz',
  path: '/blitz',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendamentosRoute =
  AuthenticatedAgendamentosRouteImport.update({
    id: '/agendamentos',
    path: '/agendamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjetosIndexRoute =
  AuthenticatedProjetosIndexRouteImport.update({
    id: '/projetos/',
    path: '/projetos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOfertaAtivaIndexRoute =
  AuthenticatedOfertaAtivaIndexRouteImport.update({
    id: '/oferta-ativa/',
    path: '/oferta-ativa/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicMetricasRoute = ApiPublicMetricasRouteImport.update({
  id: '/api/public/metricas',
  path: '/api/public/metricas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjetosProjetoIdRoute =
  AuthenticatedProjetosProjetoIdRouteImport.update({
    id: '/projetos/$projetoId',
    path: '/projetos/$projetoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOfertaAtivaNovaRoute =
  AuthenticatedOfertaAtivaNovaRouteImport.update({
    id: '/oferta-ativa/nova',
    path: '/oferta-ativa/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOfertaAtivaOfertaIdRoute =
  AuthenticatedOfertaAtivaOfertaIdRouteImport.update({
    id: '/oferta-ativa/$ofertaId',
    path: '/oferta-ativa/$ofertaId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadsLeadIdRoute =
  AuthenticatedLeadsLeadIdRouteImport.update({
    id: '/leads/$leadId',
    path: '/leads/$leadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicVendasIndexRoute = ApiPublicVendasIndexRouteImport.update({
  id: '/api/public/vendas/',
  path: '/api/public/vendas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProjetosIndexRoute = ApiPublicProjetosIndexRouteImport.update({
  id: '/api/public/projetos/',
  path: '/api/public/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsIndexRoute = ApiPublicLeadsIndexRouteImport.update({
  id: '/api/public/leads/',
  path: '/api/public/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCorretoresIndexRoute =
  ApiPublicCorretoresIndexRouteImport.update({
    id: '/api/public/corretores/',
    path: '/api/public/corretores/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicComissoesIndexRoute = ApiPublicComissoesIndexRouteImport.update({
  id: '/api/public/comissoes/',
  path: '/api/public/comissoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksLandingRoute =
  ApiPublicWebhooksLandingRouteImport.update({
    id: '/api/public/webhooks/landing',
    path: '/api/public/webhooks/landing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeadsIdRoute = ApiPublicLeadsIdRouteImport.update({
  id: '/api/public/leads/$id',
  path: '/api/public/leads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPushDispatchRoute =
  ApiPublicHooksPushDispatchRouteImport.update({
    id: '/api/public/hooks/push-dispatch',
    path: '/api/public/hooks/push-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCopilotoHandoffRoute =
  ApiPublicHooksCopilotoHandoffRouteImport.update({
    id: '/api/public/hooks/copiloto-handoff',
    path: '/api/public/hooks/copiloto-handoff',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCorretoresIdRoute = ApiPublicCorretoresIdRouteImport.update({
  id: '/api/public/corretores/$id',
  path: '/api/public/corretores/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleOauthCallbackRoute = ApiGoogleOauthCallbackRouteImport.update({
  id: '/api/google/oauth/callback',
  path: '/api/google/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksLeadTokenRoute =
  ApiPublicWebhooksLeadTokenRouteImport.update({
    id: '/api/public/webhooks/lead/$token',
    path: '/api/public/webhooks/lead/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeadsIdPerdaRoute = ApiPublicLeadsIdPerdaRouteImport.update({
  id: '/perda',
  path: '/perda',
  getParentRoute: () => ApiPublicLeadsIdRoute,
} as any)
const ApiPublicLeadsIdEventosRoute = ApiPublicLeadsIdEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => ApiPublicLeadsIdRoute,
} as any)
const ApiPublicLeadsIdCorretorRoute =
  ApiPublicLeadsIdCorretorRouteImport.update({
    id: '/corretor',
    path: '/corretor',
    getParentRoute: () => ApiPublicLeadsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agendamentos': typeof AuthenticatedAgendamentosRoute
  '/blitz': typeof AuthenticatedBlitzRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conquistas': typeof AuthenticatedConquistasRoute
  '/copa': typeof AuthenticatedCopaRoute
  '/corretores': typeof AuthenticatedCorretoresRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/distribuicao': typeof AuthenticatedDistribuicaoRoute
  '/duplicatas': typeof AuthenticatedDuplicatasRoute
  '/equipes': typeof AuthenticatedEquipesRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/leads-landing': typeof AuthenticatedLeadsLandingRoute
  '/leads-por-corretor': typeof AuthenticatedLeadsPorCorretorRoute
  '/links-uteis': typeof AuthenticatedLinksUteisRoute
  '/lixeira': typeof AuthenticatedLixeiraRoute
  '/match': typeof AuthenticatedMatchRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/meu-painel': typeof AuthenticatedMeuPainelRoute
  '/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/painel-gestor': typeof AuthenticatedPainelGestorRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/oferta-ativa/$ofertaId': typeof AuthenticatedOfertaAtivaOfertaIdRoute
  '/oferta-ativa/nova': typeof AuthenticatedOfertaAtivaNovaRoute
  '/projetos/$projetoId': typeof AuthenticatedProjetosProjetoIdRoute
  '/api/public/metricas': typeof ApiPublicMetricasRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
  '/oferta-ativa/': typeof AuthenticatedOfertaAtivaIndexRoute
  '/projetos/': typeof AuthenticatedProjetosIndexRoute
  '/api/google/oauth/callback': typeof ApiGoogleOauthCallbackRoute
  '/api/public/corretores/$id': typeof ApiPublicCorretoresIdRoute
  '/api/public/hooks/copiloto-handoff': typeof ApiPublicHooksCopilotoHandoffRoute
  '/api/public/hooks/push-dispatch': typeof ApiPublicHooksPushDispatchRoute
  '/api/public/leads/$id': typeof ApiPublicLeadsIdRouteWithChildren
  '/api/public/webhooks/landing': typeof ApiPublicWebhooksLandingRoute
  '/api/public/comissoes/': typeof ApiPublicComissoesIndexRoute
  '/api/public/corretores/': typeof ApiPublicCorretoresIndexRoute
  '/api/public/leads/': typeof ApiPublicLeadsIndexRoute
  '/api/public/projetos/': typeof ApiPublicProjetosIndexRoute
  '/api/public/vendas/': typeof ApiPublicVendasIndexRoute
  '/api/public/leads/$id/corretor': typeof ApiPublicLeadsIdCorretorRoute
  '/api/public/leads/$id/eventos': typeof ApiPublicLeadsIdEventosRoute
  '/api/public/leads/$id/perda': typeof ApiPublicLeadsIdPerdaRoute
  '/api/public/webhooks/lead/$token': typeof ApiPublicWebhooksLeadTokenRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agendamentos': typeof AuthenticatedAgendamentosRoute
  '/blitz': typeof AuthenticatedBlitzRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conquistas': typeof AuthenticatedConquistasRoute
  '/copa': typeof AuthenticatedCopaRoute
  '/corretores': typeof AuthenticatedCorretoresRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/distribuicao': typeof AuthenticatedDistribuicaoRoute
  '/duplicatas': typeof AuthenticatedDuplicatasRoute
  '/equipes': typeof AuthenticatedEquipesRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/leads-landing': typeof AuthenticatedLeadsLandingRoute
  '/leads-por-corretor': typeof AuthenticatedLeadsPorCorretorRoute
  '/links-uteis': typeof AuthenticatedLinksUteisRoute
  '/lixeira': typeof AuthenticatedLixeiraRoute
  '/match': typeof AuthenticatedMatchRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/meu-painel': typeof AuthenticatedMeuPainelRoute
  '/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/painel-gestor': typeof AuthenticatedPainelGestorRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/': typeof AuthenticatedIndexRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/oferta-ativa/$ofertaId': typeof AuthenticatedOfertaAtivaOfertaIdRoute
  '/oferta-ativa/nova': typeof AuthenticatedOfertaAtivaNovaRoute
  '/projetos/$projetoId': typeof AuthenticatedProjetosProjetoIdRoute
  '/api/public/metricas': typeof ApiPublicMetricasRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
  '/oferta-ativa': typeof AuthenticatedOfertaAtivaIndexRoute
  '/projetos': typeof AuthenticatedProjetosIndexRoute
  '/api/google/oauth/callback': typeof ApiGoogleOauthCallbackRoute
  '/api/public/corretores/$id': typeof ApiPublicCorretoresIdRoute
  '/api/public/hooks/copiloto-handoff': typeof ApiPublicHooksCopilotoHandoffRoute
  '/api/public/hooks/push-dispatch': typeof ApiPublicHooksPushDispatchRoute
  '/api/public/leads/$id': typeof ApiPublicLeadsIdRouteWithChildren
  '/api/public/webhooks/landing': typeof ApiPublicWebhooksLandingRoute
  '/api/public/comissoes': typeof ApiPublicComissoesIndexRoute
  '/api/public/corretores': typeof ApiPublicCorretoresIndexRoute
  '/api/public/leads': typeof ApiPublicLeadsIndexRoute
  '/api/public/projetos': typeof ApiPublicProjetosIndexRoute
  '/api/public/vendas': typeof ApiPublicVendasIndexRoute
  '/api/public/leads/$id/corretor': typeof ApiPublicLeadsIdCorretorRoute
  '/api/public/leads/$id/eventos': typeof ApiPublicLeadsIdEventosRoute
  '/api/public/leads/$id/perda': typeof ApiPublicLeadsIdPerdaRoute
  '/api/public/webhooks/lead/$token': typeof ApiPublicWebhooksLeadTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/agendamentos': typeof AuthenticatedAgendamentosRoute
  '/_authenticated/blitz': typeof AuthenticatedBlitzRoute
  '/_authenticated/comissoes': typeof AuthenticatedComissoesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/conquistas': typeof AuthenticatedConquistasRoute
  '/_authenticated/copa': typeof AuthenticatedCopaRoute
  '/_authenticated/corretores': typeof AuthenticatedCorretoresRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/distribuicao': typeof AuthenticatedDistribuicaoRoute
  '/_authenticated/duplicatas': typeof AuthenticatedDuplicatasRoute
  '/_authenticated/equipes': typeof AuthenticatedEquipesRoute
  '/_authenticated/hoje': typeof AuthenticatedHojeRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/leads-landing': typeof AuthenticatedLeadsLandingRoute
  '/_authenticated/leads-por-corretor': typeof AuthenticatedLeadsPorCorretorRoute
  '/_authenticated/links-uteis': typeof AuthenticatedLinksUteisRoute
  '/_authenticated/lixeira': typeof AuthenticatedLixeiraRoute
  '/_authenticated/match': typeof AuthenticatedMatchRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/meu-painel': typeof AuthenticatedMeuPainelRoute
  '/_authenticated/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/_authenticated/painel-gestor': typeof AuthenticatedPainelGestorRoute
  '/_authenticated/radar': typeof AuthenticatedRadarRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/_authenticated/oferta-ativa/$ofertaId': typeof AuthenticatedOfertaAtivaOfertaIdRoute
  '/_authenticated/oferta-ativa/nova': typeof AuthenticatedOfertaAtivaNovaRoute
  '/_authenticated/projetos/$projetoId': typeof AuthenticatedProjetosProjetoIdRoute
  '/api/public/metricas': typeof ApiPublicMetricasRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
  '/_authenticated/oferta-ativa/': typeof AuthenticatedOfertaAtivaIndexRoute
  '/_authenticated/projetos/': typeof AuthenticatedProjetosIndexRoute
  '/api/google/oauth/callback': typeof ApiGoogleOauthCallbackRoute
  '/api/public/corretores/$id': typeof ApiPublicCorretoresIdRoute
  '/api/public/hooks/copiloto-handoff': typeof ApiPublicHooksCopilotoHandoffRoute
  '/api/public/hooks/push-dispatch': typeof ApiPublicHooksPushDispatchRoute
  '/api/public/leads/$id': typeof ApiPublicLeadsIdRouteWithChildren
  '/api/public/webhooks/landing': typeof ApiPublicWebhooksLandingRoute
  '/api/public/comissoes/': typeof ApiPublicComissoesIndexRoute
  '/api/public/corretores/': typeof ApiPublicCorretoresIndexRoute
  '/api/public/leads/': typeof ApiPublicLeadsIndexRoute
  '/api/public/projetos/': typeof ApiPublicProjetosIndexRoute
  '/api/public/vendas/': typeof ApiPublicVendasIndexRoute
  '/api/public/leads/$id/corretor': typeof ApiPublicLeadsIdCorretorRoute
  '/api/public/leads/$id/eventos': typeof ApiPublicLeadsIdEventosRoute
  '/api/public/leads/$id/perda': typeof ApiPublicLeadsIdPerdaRoute
  '/api/public/webhooks/lead/$token': typeof ApiPublicWebhooksLeadTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/agendamentos'
    | '/blitz'
    | '/comissoes'
    | '/configuracoes'
    | '/conquistas'
    | '/copa'
    | '/corretores'
    | '/dashboard'
    | '/distribuicao'
    | '/duplicatas'
    | '/equipes'
    | '/hoje'
    | '/kanban'
    | '/leads-landing'
    | '/leads-por-corretor'
    | '/links-uteis'
    | '/lixeira'
    | '/match'
    | '/metas'
    | '/meu-painel'
    | '/meu-perfil'
    | '/painel-gestor'
    | '/radar'
    | '/ranking'
    | '/relatorios'
    | '/tarefas'
    | '/templates'
    | '/leads/$leadId'
    | '/oferta-ativa/$ofertaId'
    | '/oferta-ativa/nova'
    | '/projetos/$projetoId'
    | '/api/public/metricas'
    | '/leads/'
    | '/oferta-ativa/'
    | '/projetos/'
    | '/api/google/oauth/callback'
    | '/api/public/corretores/$id'
    | '/api/public/hooks/copiloto-handoff'
    | '/api/public/hooks/push-dispatch'
    | '/api/public/leads/$id'
    | '/api/public/webhooks/landing'
    | '/api/public/comissoes/'
    | '/api/public/corretores/'
    | '/api/public/leads/'
    | '/api/public/projetos/'
    | '/api/public/vendas/'
    | '/api/public/leads/$id/corretor'
    | '/api/public/leads/$id/eventos'
    | '/api/public/leads/$id/perda'
    | '/api/public/webhooks/lead/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/agendamentos'
    | '/blitz'
    | '/comissoes'
    | '/configuracoes'
    | '/conquistas'
    | '/copa'
    | '/corretores'
    | '/dashboard'
    | '/distribuicao'
    | '/duplicatas'
    | '/equipes'
    | '/hoje'
    | '/kanban'
    | '/leads-landing'
    | '/leads-por-corretor'
    | '/links-uteis'
    | '/lixeira'
    | '/match'
    | '/metas'
    | '/meu-painel'
    | '/meu-perfil'
    | '/painel-gestor'
    | '/radar'
    | '/ranking'
    | '/relatorios'
    | '/tarefas'
    | '/templates'
    | '/'
    | '/leads/$leadId'
    | '/oferta-ativa/$ofertaId'
    | '/oferta-ativa/nova'
    | '/projetos/$projetoId'
    | '/api/public/metricas'
    | '/leads'
    | '/oferta-ativa'
    | '/projetos'
    | '/api/google/oauth/callback'
    | '/api/public/corretores/$id'
    | '/api/public/hooks/copiloto-handoff'
    | '/api/public/hooks/push-dispatch'
    | '/api/public/leads/$id'
    | '/api/public/webhooks/landing'
    | '/api/public/comissoes'
    | '/api/public/corretores'
    | '/api/public/leads'
    | '/api/public/projetos'
    | '/api/public/vendas'
    | '/api/public/leads/$id/corretor'
    | '/api/public/leads/$id/eventos'
    | '/api/public/leads/$id/perda'
    | '/api/public/webhooks/lead/$token'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/agendamentos'
    | '/_authenticated/blitz'
    | '/_authenticated/comissoes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/conquistas'
    | '/_authenticated/copa'
    | '/_authenticated/corretores'
    | '/_authenticated/dashboard'
    | '/_authenticated/distribuicao'
    | '/_authenticated/duplicatas'
    | '/_authenticated/equipes'
    | '/_authenticated/hoje'
    | '/_authenticated/kanban'
    | '/_authenticated/leads-landing'
    | '/_authenticated/leads-por-corretor'
    | '/_authenticated/links-uteis'
    | '/_authenticated/lixeira'
    | '/_authenticated/match'
    | '/_authenticated/metas'
    | '/_authenticated/meu-painel'
    | '/_authenticated/meu-perfil'
    | '/_authenticated/painel-gestor'
    | '/_authenticated/radar'
    | '/_authenticated/ranking'
    | '/_authenticated/relatorios'
    | '/_authenticated/tarefas'
    | '/_authenticated/templates'
    | '/_authenticated/'
    | '/_authenticated/leads/$leadId'
    | '/_authenticated/oferta-ativa/$ofertaId'
    | '/_authenticated/oferta-ativa/nova'
    | '/_authenticated/projetos/$projetoId'
    | '/api/public/metricas'
    | '/_authenticated/leads/'
    | '/_authenticated/oferta-ativa/'
    | '/_authenticated/projetos/'
    | '/api/google/oauth/callback'
    | '/api/public/corretores/$id'
    | '/api/public/hooks/copiloto-handoff'
    | '/api/public/hooks/push-dispatch'
    | '/api/public/leads/$id'
    | '/api/public/webhooks/landing'
    | '/api/public/comissoes/'
    | '/api/public/corretores/'
    | '/api/public/leads/'
    | '/api/public/projetos/'
    | '/api/public/vendas/'
    | '/api/public/leads/$id/corretor'
    | '/api/public/leads/$id/eventos'
    | '/api/public/leads/$id/perda'
    | '/api/public/webhooks/lead/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicMetricasRoute: typeof ApiPublicMetricasRoute
  ApiGoogleOauthCallbackRoute: typeof ApiGoogleOauthCallbackRoute
  ApiPublicCorretoresIdRoute: typeof ApiPublicCorretoresIdRoute
  ApiPublicHooksCopilotoHandoffRoute: typeof ApiPublicHooksCopilotoHandoffRoute
  ApiPublicHooksPushDispatchRoute: typeof ApiPublicHooksPushDispatchRoute
  ApiPublicLeadsIdRoute: typeof ApiPublicLeadsIdRouteWithChildren
  ApiPublicWebhooksLandingRoute: typeof ApiPublicWebhooksLandingRoute
  ApiPublicComissoesIndexRoute: typeof ApiPublicComissoesIndexRoute
  ApiPublicCorretoresIndexRoute: typeof ApiPublicCorretoresIndexRoute
  ApiPublicLeadsIndexRoute: typeof ApiPublicLeadsIndexRoute
  ApiPublicProjetosIndexRoute: typeof ApiPublicProjetosIndexRoute
  ApiPublicVendasIndexRoute: typeof ApiPublicVendasIndexRoute
  ApiPublicWebhooksLeadTokenRoute: typeof ApiPublicWebhooksLeadTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radar': {
      id: '/_authenticated/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof AuthenticatedRadarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel-gestor': {
      id: '/_authenticated/painel-gestor'
      path: '/painel-gestor'
      fullPath: '/painel-gestor'
      preLoaderRoute: typeof AuthenticatedPainelGestorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-perfil': {
      id: '/_authenticated/meu-perfil'
      path: '/meu-perfil'
      fullPath: '/meu-perfil'
      preLoaderRoute: typeof AuthenticatedMeuPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-painel': {
      id: '/_authenticated/meu-painel'
      path: '/meu-painel'
      fullPath: '/meu-painel'
      preLoaderRoute: typeof AuthenticatedMeuPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/match': {
      id: '/_authenticated/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof AuthenticatedMatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lixeira': {
      id: '/_authenticated/lixeira'
      path: '/lixeira'
      fullPath: '/lixeira'
      preLoaderRoute: typeof AuthenticatedLixeiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/links-uteis': {
      id: '/_authenticated/links-uteis'
      path: '/links-uteis'
      fullPath: '/links-uteis'
      preLoaderRoute: typeof AuthenticatedLinksUteisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads-por-corretor': {
      id: '/_authenticated/leads-por-corretor'
      path: '/leads-por-corretor'
      fullPath: '/leads-por-corretor'
      preLoaderRoute: typeof AuthenticatedLeadsPorCorretorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads-landing': {
      id: '/_authenticated/leads-landing'
      path: '/leads-landing'
      fullPath: '/leads-landing'
      preLoaderRoute: typeof AuthenticatedLeadsLandingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hoje': {
      id: '/_authenticated/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof AuthenticatedHojeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipes': {
      id: '/_authenticated/equipes'
      path: '/equipes'
      fullPath: '/equipes'
      preLoaderRoute: typeof AuthenticatedEquipesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/duplicatas': {
      id: '/_authenticated/duplicatas'
      path: '/duplicatas'
      fullPath: '/duplicatas'
      preLoaderRoute: typeof AuthenticatedDuplicatasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/distribuicao': {
      id: '/_authenticated/distribuicao'
      path: '/distribuicao'
      fullPath: '/distribuicao'
      preLoaderRoute: typeof AuthenticatedDistribuicaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/corretores': {
      id: '/_authenticated/corretores'
      path: '/corretores'
      fullPath: '/corretores'
      preLoaderRoute: typeof AuthenticatedCorretoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copa': {
      id: '/_authenticated/copa'
      path: '/copa'
      fullPath: '/copa'
      preLoaderRoute: typeof AuthenticatedCopaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conquistas': {
      id: '/_authenticated/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof AuthenticatedConquistasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comissoes': {
      id: '/_authenticated/comissoes'
      path: '/comissoes'
      fullPath: '/comissoes'
      preLoaderRoute: typeof AuthenticatedComissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blitz': {
      id: '/_authenticated/blitz'
      path: '/blitz'
      fullPath: '/blitz'
      preLoaderRoute: typeof AuthenticatedBlitzRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agendamentos': {
      id: '/_authenticated/agendamentos'
      path: '/agendamentos'
      fullPath: '/agendamentos'
      preLoaderRoute: typeof AuthenticatedAgendamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos/': {
      id: '/_authenticated/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof AuthenticatedProjetosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oferta-ativa/': {
      id: '/_authenticated/oferta-ativa/'
      path: '/oferta-ativa'
      fullPath: '/oferta-ativa/'
      preLoaderRoute: typeof AuthenticatedOfertaAtivaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/metricas': {
      id: '/api/public/metricas'
      path: '/api/public/metricas'
      fullPath: '/api/public/metricas'
      preLoaderRoute: typeof ApiPublicMetricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projetos/$projetoId': {
      id: '/_authenticated/projetos/$projetoId'
      path: '/projetos/$projetoId'
      fullPath: '/projetos/$projetoId'
      preLoaderRoute: typeof AuthenticatedProjetosProjetoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oferta-ativa/nova': {
      id: '/_authenticated/oferta-ativa/nova'
      path: '/oferta-ativa/nova'
      fullPath: '/oferta-ativa/nova'
      preLoaderRoute: typeof AuthenticatedOfertaAtivaNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oferta-ativa/$ofertaId': {
      id: '/_authenticated/oferta-ativa/$ofertaId'
      path: '/oferta-ativa/$ofertaId'
      fullPath: '/oferta-ativa/$ofertaId'
      preLoaderRoute: typeof AuthenticatedOfertaAtivaOfertaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/$leadId': {
      id: '/_authenticated/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AuthenticatedLeadsLeadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/vendas/': {
      id: '/api/public/vendas/'
      path: '/api/public/vendas'
      fullPath: '/api/public/vendas/'
      preLoaderRoute: typeof ApiPublicVendasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/projetos/': {
      id: '/api/public/projetos/'
      path: '/api/public/projetos'
      fullPath: '/api/public/projetos/'
      preLoaderRoute: typeof ApiPublicProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/': {
      id: '/api/public/leads/'
      path: '/api/public/leads'
      fullPath: '/api/public/leads/'
      preLoaderRoute: typeof ApiPublicLeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/corretores/': {
      id: '/api/public/corretores/'
      path: '/api/public/corretores'
      fullPath: '/api/public/corretores/'
      preLoaderRoute: typeof ApiPublicCorretoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/comissoes/': {
      id: '/api/public/comissoes/'
      path: '/api/public/comissoes'
      fullPath: '/api/public/comissoes/'
      preLoaderRoute: typeof ApiPublicComissoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/landing': {
      id: '/api/public/webhooks/landing'
      path: '/api/public/webhooks/landing'
      fullPath: '/api/public/webhooks/landing'
      preLoaderRoute: typeof ApiPublicWebhooksLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/$id': {
      id: '/api/public/leads/$id'
      path: '/api/public/leads/$id'
      fullPath: '/api/public/leads/$id'
      preLoaderRoute: typeof ApiPublicLeadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/push-dispatch': {
      id: '/api/public/hooks/push-dispatch'
      path: '/api/public/hooks/push-dispatch'
      fullPath: '/api/public/hooks/push-dispatch'
      preLoaderRoute: typeof ApiPublicHooksPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/copiloto-handoff': {
      id: '/api/public/hooks/copiloto-handoff'
      path: '/api/public/hooks/copiloto-handoff'
      fullPath: '/api/public/hooks/copiloto-handoff'
      preLoaderRoute: typeof ApiPublicHooksCopilotoHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/corretores/$id': {
      id: '/api/public/corretores/$id'
      path: '/api/public/corretores/$id'
      fullPath: '/api/public/corretores/$id'
      preLoaderRoute: typeof ApiPublicCorretoresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/oauth/callback': {
      id: '/api/google/oauth/callback'
      path: '/api/google/oauth/callback'
      fullPath: '/api/google/oauth/callback'
      preLoaderRoute: typeof ApiGoogleOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/lead/$token': {
      id: '/api/public/webhooks/lead/$token'
      path: '/api/public/webhooks/lead/$token'
      fullPath: '/api/public/webhooks/lead/$token'
      preLoaderRoute: typeof ApiPublicWebhooksLeadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/$id/perda': {
      id: '/api/public/leads/$id/perda'
      path: '/perda'
      fullPath: '/api/public/leads/$id/perda'
      preLoaderRoute: typeof ApiPublicLeadsIdPerdaRouteImport
      parentRoute: typeof ApiPublicLeadsIdRoute
    }
    '/api/public/leads/$id/eventos': {
      id: '/api/public/leads/$id/eventos'
      path: '/eventos'
      fullPath: '/api/public/leads/$id/eventos'
      preLoaderRoute: typeof ApiPublicLeadsIdEventosRouteImport
      parentRoute: typeof ApiPublicLeadsIdRoute
    }
    '/api/public/leads/$id/corretor': {
      id: '/api/public/leads/$id/corretor'
      path: '/corretor'
      fullPath: '/api/public/leads/$id/corretor'
      preLoaderRoute: typeof ApiPublicLeadsIdCorretorRouteImport
      parentRoute: typeof ApiPublicLeadsIdRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendamentosRoute: typeof AuthenticatedAgendamentosRoute
  AuthenticatedBlitzRoute: typeof AuthenticatedBlitzRoute
  AuthenticatedComissoesRoute: typeof AuthenticatedComissoesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConquistasRoute: typeof AuthenticatedConquistasRoute
  AuthenticatedCopaRoute: typeof AuthenticatedCopaRoute
  AuthenticatedCorretoresRoute: typeof AuthenticatedCorretoresRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDistribuicaoRoute: typeof AuthenticatedDistribuicaoRoute
  AuthenticatedDuplicatasRoute: typeof AuthenticatedDuplicatasRoute
  AuthenticatedEquipesRoute: typeof AuthenticatedEquipesRoute
  AuthenticatedHojeRoute: typeof AuthenticatedHojeRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedLeadsLandingRoute: typeof AuthenticatedLeadsLandingRoute
  AuthenticatedLeadsPorCorretorRoute: typeof AuthenticatedLeadsPorCorretorRoute
  AuthenticatedLinksUteisRoute: typeof AuthenticatedLinksUteisRoute
  AuthenticatedLixeiraRoute: typeof AuthenticatedLixeiraRoute
  AuthenticatedMatchRoute: typeof AuthenticatedMatchRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedMeuPainelRoute: typeof AuthenticatedMeuPainelRoute
  AuthenticatedMeuPerfilRoute: typeof AuthenticatedMeuPerfilRoute
  AuthenticatedPainelGestorRoute: typeof AuthenticatedPainelGestorRoute
  AuthenticatedRadarRoute: typeof AuthenticatedRadarRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedLeadsLeadIdRoute: typeof AuthenticatedLeadsLeadIdRoute
  AuthenticatedOfertaAtivaOfertaIdRoute: typeof AuthenticatedOfertaAtivaOfertaIdRoute
  AuthenticatedOfertaAtivaNovaRoute: typeof AuthenticatedOfertaAtivaNovaRoute
  AuthenticatedProjetosProjetoIdRoute: typeof AuthenticatedProjetosProjetoIdRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
  AuthenticatedOfertaAtivaIndexRoute: typeof AuthenticatedOfertaAtivaIndexRoute
  AuthenticatedProjetosIndexRoute: typeof AuthenticatedProjetosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendamentosRoute: AuthenticatedAgendamentosRoute,
  AuthenticatedBlitzRoute: AuthenticatedBlitzRoute,
  AuthenticatedComissoesRoute: AuthenticatedComissoesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConquistasRoute: AuthenticatedConquistasRoute,
  AuthenticatedCopaRoute: AuthenticatedCopaRoute,
  AuthenticatedCorretoresRoute: AuthenticatedCorretoresRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDistribuicaoRoute: AuthenticatedDistribuicaoRoute,
  AuthenticatedDuplicatasRoute: AuthenticatedDuplicatasRoute,
  AuthenticatedEquipesRoute: AuthenticatedEquipesRoute,
  AuthenticatedHojeRoute: AuthenticatedHojeRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedLeadsLandingRoute: AuthenticatedLeadsLandingRoute,
  AuthenticatedLeadsPorCorretorRoute: AuthenticatedLeadsPorCorretorRoute,
  AuthenticatedLinksUteisRoute: AuthenticatedLinksUteisRoute,
  AuthenticatedLixeiraRoute: AuthenticatedLixeiraRoute,
  AuthenticatedMatchRoute: AuthenticatedMatchRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedMeuPainelRoute: AuthenticatedMeuPainelRoute,
  AuthenticatedMeuPerfilRoute: AuthenticatedMeuPerfilRoute,
  AuthenticatedPainelGestorRoute: AuthenticatedPainelGestorRoute,
  AuthenticatedRadarRoute: AuthenticatedRadarRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedLeadsLeadIdRoute: AuthenticatedLeadsLeadIdRoute,
  AuthenticatedOfertaAtivaOfertaIdRoute: AuthenticatedOfertaAtivaOfertaIdRoute,
  AuthenticatedOfertaAtivaNovaRoute: AuthenticatedOfertaAtivaNovaRoute,
  AuthenticatedProjetosProjetoIdRoute: AuthenticatedProjetosProjetoIdRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
  AuthenticatedOfertaAtivaIndexRoute: AuthenticatedOfertaAtivaIndexRoute,
  AuthenticatedProjetosIndexRoute: AuthenticatedProjetosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicLeadsIdRouteChildren {
  ApiPublicLeadsIdCorretorRoute: typeof ApiPublicLeadsIdCorretorRoute
  ApiPublicLeadsIdEventosRoute: typeof ApiPublicLeadsIdEventosRoute
  ApiPublicLeadsIdPerdaRoute: typeof ApiPublicLeadsIdPerdaRoute
}

const ApiPublicLeadsIdRouteChildren: ApiPublicLeadsIdRouteChildren = {
  ApiPublicLeadsIdCorretorRoute: ApiPublicLeadsIdCorretorRoute,
  ApiPublicLeadsIdEventosRoute: ApiPublicLeadsIdEventosRoute,
  ApiPublicLeadsIdPerdaRoute: ApiPublicLeadsIdPerdaRoute,
}

const ApiPublicLeadsIdRouteWithChildren =
  ApiPublicLeadsIdRoute._addFileChildren(ApiPublicLeadsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicMetricasRoute: ApiPublicMetricasRoute,
  ApiGoogleOauthCallbackRoute: ApiGoogleOauthCallbackRoute,
  ApiPublicCorretoresIdRoute: ApiPublicCorretoresIdRoute,
  ApiPublicHooksCopilotoHandoffRoute: ApiPublicHooksCopilotoHandoffRoute,
  ApiPublicHooksPushDispatchRoute: ApiPublicHooksPushDispatchRoute,
  ApiPublicLeadsIdRoute: ApiPublicLeadsIdRouteWithChildren,
  ApiPublicWebhooksLandingRoute: ApiPublicWebhooksLandingRoute,
  ApiPublicComissoesIndexRoute: ApiPublicComissoesIndexRoute,
  ApiPublicCorretoresIndexRoute: ApiPublicCorretoresIndexRoute,
  ApiPublicLeadsIndexRoute: ApiPublicLeadsIndexRoute,
  ApiPublicProjetosIndexRoute: ApiPublicProjetosIndexRoute,
  ApiPublicVendasIndexRoute: ApiPublicVendasIndexRoute,
  ApiPublicWebhooksLeadTokenRoute: ApiPublicWebhooksLeadTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
