-- Vitrine pública segura: shortlist de 2–3 projetos vinculada internamente a
-- um lead, mas sem PII na URL ou na resposta pública. O token bruto existe
-- apenas no processo que cria o link; o banco persiste somente SHA-256.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type WHERE typnamespace = 'public'::regnamespace
      AND typname = 'vitrine_evento_tipo'
  ) THEN
    CREATE TYPE public.vitrine_evento_tipo AS ENUM (
      'abertura',
      'projeto_visto',
      'cta_clicado'
    );
  END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS public.vitrine_links (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id uuid NOT NULL REFERENCES public.leads(id) ON DELETE CASCADE,
  criado_por uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  token_hash text NOT NULL,
  expira_em timestamptz NOT NULL,
  revogado_em timestamptz,
  revogado_por uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  ultimo_acesso_em timestamptz,
  total_aberturas integer NOT NULL DEFAULT 0 CHECK (total_aberturas >= 0),
  total_eventos integer NOT NULL DEFAULT 0 CHECK (total_eventos BETWEEN 0 AND 1000),
  total_requisicoes integer NOT NULL DEFAULT 0 CHECK (total_requisicoes BETWEEN 0 AND 20000),
  limite_janela_inicio timestamptz,
  limite_janela_requisicoes integer NOT NULL DEFAULT 0
    CHECK (limite_janela_requisicoes BETWEEN 0 AND 60),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT vitrine_links_token_hash_formato_ck
    CHECK (token_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT vitrine_links_validade_ck
    CHECK (expira_em > created_at AND expira_em <= created_at + interval '30 days'),
  CONSTRAINT vitrine_links_revogacao_ck
    CHECK (
      (revogado_em IS NULL AND revogado_por IS NULL)
      OR (revogado_em IS NOT NULL)
    )
);

-- Compatibilidade com eventual aplicação de uma revisão intermediária desta
-- migration no ambiente vivo desconhecido.
ALTER TABLE public.vitrine_links
  ADD COLUMN IF NOT EXISTS total_eventos integer NOT NULL DEFAULT 0
    CHECK (total_eventos BETWEEN 0 AND 1000),
  ADD COLUMN IF NOT EXISTS total_requisicoes integer NOT NULL DEFAULT 0
    CHECK (total_requisicoes BETWEEN 0 AND 20000),
  ADD COLUMN IF NOT EXISTS limite_janela_inicio timestamptz,
  ADD COLUMN IF NOT EXISTS limite_janela_requisicoes integer NOT NULL DEFAULT 0
    CHECK (limite_janela_requisicoes BETWEEN 0 AND 60);

CREATE UNIQUE INDEX IF NOT EXISTS uq_vitrine_links_token_hash
  ON public.vitrine_links (token_hash);
CREATE INDEX IF NOT EXISTS idx_vitrine_links_lead_created
  ON public.vitrine_links (lead_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_vitrine_links_validos
  ON public.vitrine_links (expira_em)
  WHERE revogado_em IS NULL;

CREATE TABLE IF NOT EXISTS public.vitrine_link_projetos (
  link_id uuid NOT NULL REFERENCES public.vitrine_links(id) ON DELETE CASCADE,
  projeto_id uuid NOT NULL REFERENCES public.projetos(id) ON DELETE RESTRICT,
  ordem smallint NOT NULL CHECK (ordem BETWEEN 1 AND 3),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (link_id, projeto_id),
  CONSTRAINT uq_vitrine_link_projetos_ordem UNIQUE (link_id, ordem)
);

CREATE INDEX IF NOT EXISTS idx_vitrine_link_projetos_projeto
  ON public.vitrine_link_projetos (projeto_id, link_id);

CREATE TABLE IF NOT EXISTS public.vitrine_link_eventos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  link_id uuid NOT NULL REFERENCES public.vitrine_links(id) ON DELETE CASCADE,
  projeto_id uuid REFERENCES public.projetos(id) ON DELETE RESTRICT,
  tipo public.vitrine_evento_tipo NOT NULL,
  cta_tipo text,
  idempotency_key uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT vitrine_link_eventos_contexto_ck CHECK (
    (tipo = 'abertura' AND projeto_id IS NULL AND cta_tipo IS NULL)
    OR (tipo = 'projeto_visto' AND projeto_id IS NOT NULL AND cta_tipo IS NULL)
    OR (
      tipo = 'cta_clicado'
      AND projeto_id IS NOT NULL
      AND cta_tipo IN ('book', 'tabela_precos', 'contato')
    )
  )
);

ALTER TABLE public.vitrine_link_eventos
  ADD COLUMN IF NOT EXISTS idempotency_key uuid;
UPDATE public.vitrine_link_eventos
SET idempotency_key = gen_random_uuid()
WHERE idempotency_key IS NULL;
ALTER TABLE public.vitrine_link_eventos
  ALTER COLUMN idempotency_key SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_vitrine_eventos_idempotencia
  ON public.vitrine_link_eventos (link_id, idempotency_key);

CREATE INDEX IF NOT EXISTS idx_vitrine_link_eventos_link_created
  ON public.vitrine_link_eventos (link_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_vitrine_link_eventos_projeto_created
  ON public.vitrine_link_eventos (projeto_id, created_at DESC)
  WHERE projeto_id IS NOT NULL;

ALTER TABLE public.vitrine_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vitrine_link_projetos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vitrine_link_eventos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vitrine_links FORCE ROW LEVEL SECURITY;
ALTER TABLE public.vitrine_link_projetos FORCE ROW LEVEL SECURITY;
ALTER TABLE public.vitrine_link_eventos FORCE ROW LEVEL SECURITY;

-- O navegador nunca consulta estas tabelas. A service role chama somente as
-- funções estreitas abaixo depois de autenticar o usuário ou validar o hash.
REVOKE ALL ON public.vitrine_links FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.vitrine_link_projetos FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.vitrine_link_eventos FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.vitrine_links TO service_role;
GRANT ALL ON public.vitrine_link_projetos TO service_role;
GRANT ALL ON public.vitrine_link_eventos TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.vitrine_link_eventos_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.criar_vitrine_link(
  _ator_id uuid,
  _lead_id uuid,
  _token_hash text,
  _projeto_ids uuid[],
  _expira_em timestamptz
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  _link_id uuid;
  _quantidade integer;
  _projetos_validos integer;
BEGIN
  IF _ator_id IS NULL
     OR NOT public.is_active_member(_ator_id)
     OR NOT public.pode_acessar_lead(_ator_id, _lead_id) THEN
    RAISE EXCEPTION 'vitrine_link_forbidden' USING ERRCODE = '42501';
  END IF;

  IF _token_hash IS NULL OR lower(_token_hash) !~ '^[0-9a-f]{64}$' THEN
    RAISE EXCEPTION 'vitrine_token_hash_invalido' USING ERRCODE = '22023';
  END IF;

  _quantidade := cardinality(_projeto_ids);
  IF _quantidade IS NULL OR _quantidade < 2 OR _quantidade > 3
     OR array_position(_projeto_ids, NULL) IS NOT NULL
     OR (SELECT count(DISTINCT id) FROM unnest(_projeto_ids) AS ids(id)) <> _quantidade THEN
    RAISE EXCEPTION 'vitrine_shortlist_invalida' USING ERRCODE = '22023';
  END IF;

  IF _expira_em <= now() OR _expira_em > now() + interval '30 days' THEN
    RAISE EXCEPTION 'vitrine_validade_invalida' USING ERRCODE = '22023';
  END IF;

  SELECT count(*)
    INTO _projetos_validos
    FROM public.projetos p
   WHERE p.id = ANY (_projeto_ids)
     AND p.ativo = true
     AND p.deleted_at IS NULL;

  IF _projetos_validos <> _quantidade THEN
    RAISE EXCEPTION 'vitrine_projeto_indisponivel' USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.vitrine_links (
    lead_id, criado_por, token_hash, expira_em
  ) VALUES (
    _lead_id, _ator_id, lower(_token_hash), _expira_em
  )
  RETURNING id INTO _link_id;

  INSERT INTO public.vitrine_link_projetos (link_id, projeto_id, ordem)
  SELECT _link_id, item.projeto_id, item.ordem::smallint
    FROM unnest(_projeto_ids) WITH ORDINALITY AS item(projeto_id, ordem);

  RETURN _link_id;
END;
$$;

REVOKE ALL ON FUNCTION public.criar_vitrine_link(uuid, uuid, text, uuid[], timestamptz)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.criar_vitrine_link(uuid, uuid, text, uuid[], timestamptz)
  TO service_role;

CREATE OR REPLACE FUNCTION public.revogar_vitrine_link(
  _ator_id uuid,
  _link_id uuid
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  _lead_id uuid;
BEGIN
  SELECT vl.lead_id
    INTO _lead_id
    FROM public.vitrine_links vl
   WHERE vl.id = _link_id;

  IF _lead_id IS NULL
     OR NOT public.is_active_member(_ator_id)
     OR NOT public.pode_acessar_lead(_ator_id, _lead_id) THEN
    RETURN false;
  END IF;

  UPDATE public.vitrine_links
     SET revogado_em = now(), revogado_por = _ator_id
   WHERE id = _link_id
     AND revogado_em IS NULL;

  RETURN FOUND;
END;
$$;

REVOKE ALL ON FUNCTION public.revogar_vitrine_link(uuid, uuid)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.revogar_vitrine_link(uuid, uuid)
  TO service_role;

CREATE OR REPLACE FUNCTION public.listar_vitrine_links(
  _ator_id uuid,
  _lead_id uuid
)
RETURNS TABLE (
  id uuid,
  expira_em timestamptz,
  revogado_em timestamptz,
  created_at timestamptz,
  projetos jsonb
)
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF NOT public.is_active_member(_ator_id)
     OR NOT public.pode_acessar_lead(_ator_id, _lead_id) THEN
    RAISE EXCEPTION 'vitrine_link_forbidden' USING ERRCODE = '42501';
  END IF;

  RETURN QUERY
  SELECT
    vl.id,
    vl.expira_em,
    vl.revogado_em,
    vl.created_at,
    jsonb_agg(
      jsonb_build_object(
        'id', p.id,
        'nome', p.nome,
        'ordem', vlp.ordem
      ) ORDER BY vlp.ordem
    ) AS projetos
  FROM public.vitrine_links vl
  JOIN public.vitrine_link_projetos vlp ON vlp.link_id = vl.id
  JOIN public.projetos p ON p.id = vlp.projeto_id
  WHERE vl.lead_id = _lead_id
  GROUP BY vl.id
  ORDER BY vl.created_at DESC
  LIMIT 20;
END;
$$;

REVOKE ALL ON FUNCTION public.listar_vitrine_links(uuid, uuid)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.listar_vitrine_links(uuid, uuid)
  TO service_role;

-- Limite distribuído aplicado ANTES de servir qualquer payload ou aceitar
-- evento. O lock da linha serializa instâncias serverless e o teto vitalício
-- mantém o custo de um link comprometido estritamente limitado.
CREATE OR REPLACE FUNCTION public.consumir_vitrine_requisicao(
  _token_hash text
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  _link public.vitrine_links%ROWTYPE;
  _agora timestamptz := clock_timestamp();
  _inicio timestamptz;
  _quantidade integer;
BEGIN
  IF _token_hash IS NULL OR lower(_token_hash) !~ '^[0-9a-f]{64}$' THEN
    RETURN 'not_found';
  END IF;

  SELECT * INTO _link
  FROM public.vitrine_links
  WHERE token_hash = lower(_token_hash)
    AND revogado_em IS NULL
    AND expira_em > _agora
  FOR UPDATE;

  IF NOT FOUND THEN RETURN 'not_found'; END IF;
  IF _link.total_requisicoes >= 20000 THEN RETURN 'exhausted'; END IF;

  IF _link.limite_janela_inicio IS NULL
     OR _link.limite_janela_inicio <= _agora - interval '1 minute' THEN
    _inicio := _agora;
    _quantidade := 1;
  ELSE
    _inicio := _link.limite_janela_inicio;
    _quantidade := _link.limite_janela_requisicoes + 1;
  END IF;

  IF _quantidade > 60 THEN RETURN 'rate_limited'; END IF;

  UPDATE public.vitrine_links
  SET limite_janela_inicio = _inicio,
      limite_janela_requisicoes = _quantidade,
      total_requisicoes = total_requisicoes + 1
  WHERE id = _link.id;

  RETURN 'allowed';
END;
$$;

REVOKE ALL ON FUNCTION public.consumir_vitrine_requisicao(text)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.consumir_vitrine_requisicao(text)
  TO service_role;

-- Projeção pública fechada. Não inclui lead_id, criado_por, token_hash,
-- observações, argumentos internos, endereço completo ou webhook_token.
CREATE OR REPLACE FUNCTION public.obter_vitrine_publica(_token_hash text)
RETURNS TABLE (
  expira_em timestamptz,
  projetos jsonb
)
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = pg_catalog, public
AS $$
  SELECT
    vl.expira_em,
    jsonb_agg(
      jsonb_build_object(
        'id', p.id,
        'nome', p.nome,
        'construtora', p.construtora,
        'bairro', p.bairro,
        'cidade', p.cidade,
        'zona', p.zona_smq,
        'dorms_min', p.dorms_min,
        'dorms_max', p.dorms_max,
        'metragem_min', p.metragem_min,
        'metragem_max', p.metragem_max,
        'preco_a_partir', p.preco_a_partir,
        'sob_consulta', p.sob_consulta,
        'status_preco', p.status_preco,
        'status_entrega', p.status_entrega,
        'mes_entrega', p.mes_entrega,
        'ano_entrega', p.ano_entrega,
        'renda_minima', p.renda_minima,
        'diferenciais', p.diferenciais,
        'book_url', p.book_url,
        'tabela_precos_url', p.tabela_precos_url
      ) ORDER BY vlp.ordem
    ) AS projetos
  FROM public.vitrine_links vl
  JOIN public.vitrine_link_projetos vlp ON vlp.link_id = vl.id
  JOIN public.projetos p ON p.id = vlp.projeto_id
  WHERE vl.token_hash = lower(_token_hash)
    AND lower(_token_hash) ~ '^[0-9a-f]{64}$'
    AND vl.revogado_em IS NULL
    AND vl.expira_em > now()
    AND p.ativo = true
    AND p.deleted_at IS NULL
  GROUP BY vl.id;
$$;

REVOKE ALL ON FUNCTION public.obter_vitrine_publica(text)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.obter_vitrine_publica(text)
  TO service_role;

CREATE OR REPLACE FUNCTION public.registrar_vitrine_evento(
  _token_hash text,
  _idempotency_key uuid,
  _tipo public.vitrine_evento_tipo,
  _projeto_id uuid DEFAULT NULL,
  _cta_tipo text DEFAULT NULL
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  _link_id uuid;
  _total_eventos integer;
  _inseridos integer;
BEGIN
  IF _token_hash IS NULL OR lower(_token_hash) !~ '^[0-9a-f]{64}$'
     OR _idempotency_key IS NULL THEN
    RETURN false;
  END IF;

  SELECT vl.id, vl.total_eventos
    INTO _link_id, _total_eventos
    FROM public.vitrine_links vl
   WHERE vl.token_hash = lower(_token_hash)
     AND vl.revogado_em IS NULL
     AND vl.expira_em > now()
   FOR UPDATE;

  IF _link_id IS NULL THEN
    RETURN false;
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.vitrine_link_eventos e
    WHERE e.link_id = _link_id AND e.idempotency_key = _idempotency_key
  ) THEN
    RETURN true;
  END IF;

  IF _total_eventos >= 1000 THEN RETURN false; END IF;

  -- Limite distribuído por link. O lock acima serializa a contagem e impede
  -- que um token válido seja usado para crescer a tabela sem teto.
  IF (
    SELECT count(*)
      FROM public.vitrine_link_eventos e
     WHERE e.link_id = _link_id
       AND e.created_at >= now() - interval '1 minute'
  ) >= 120 THEN
    RETURN false;
  END IF;

  IF _tipo = 'abertura' THEN
    IF _projeto_id IS NOT NULL OR _cta_tipo IS NOT NULL THEN RETURN false; END IF;
  ELSE
    IF _projeto_id IS NULL OR NOT EXISTS (
      SELECT 1
        FROM public.vitrine_link_projetos vlp
       WHERE vlp.link_id = _link_id AND vlp.projeto_id = _projeto_id
    ) THEN
      RETURN false;
    END IF;
    IF _tipo = 'projeto_visto' AND _cta_tipo IS NOT NULL THEN RETURN false; END IF;
    IF _tipo = 'cta_clicado'
       AND _cta_tipo NOT IN ('book', 'tabela_precos', 'contato') THEN
      RETURN false;
    END IF;
  END IF;

  INSERT INTO public.vitrine_link_eventos (
    link_id, projeto_id, tipo, cta_tipo, idempotency_key
  ) VALUES (
    _link_id, _projeto_id, _tipo, _cta_tipo, _idempotency_key
  )
  ON CONFLICT (link_id, idempotency_key) DO NOTHING;
  GET DIAGNOSTICS _inseridos = ROW_COUNT;

  IF _inseridos = 0 THEN RETURN true; END IF;

  UPDATE public.vitrine_links
  SET total_eventos = total_eventos + 1
  WHERE id = _link_id;

  IF _tipo = 'abertura' THEN
    UPDATE public.vitrine_links
       SET ultimo_acesso_em = now(), total_aberturas = total_aberturas + 1
     WHERE id = _link_id;
  END IF;

  RETURN true;
END;
$$;

REVOKE ALL ON FUNCTION public.registrar_vitrine_evento(
  text, uuid, public.vitrine_evento_tipo, uuid, text
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.registrar_vitrine_evento(
  text, uuid, public.vitrine_evento_tipo, uuid, text
) TO service_role;

-- Alvo para cron diário: elimina telemetria antiga somente de links já
-- expirados/revogados. O teto de 1.000 eventos por link continua protegendo o
-- banco mesmo se o agendamento operacional atrasar.
CREATE OR REPLACE FUNCTION public.limpar_vitrine_eventos_expirados(
  _antes timestamptz DEFAULT now() - interval '90 days'
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  _removidos integer;
BEGIN
  IF _antes > now() - interval '30 days' THEN
    RAISE EXCEPTION 'janela minima de retencao e 30 dias' USING ERRCODE = '22023';
  END IF;

  DELETE FROM public.vitrine_link_eventos AS evento
  USING public.vitrine_links AS link
  WHERE evento.link_id = link.id
    AND evento.created_at < _antes
    AND (link.revogado_em IS NOT NULL OR link.expira_em < now());
  GET DIAGNOSTICS _removidos = ROW_COUNT;
  RETURN _removidos;
END;
$$;

REVOKE ALL ON FUNCTION public.limpar_vitrine_eventos_expirados(timestamptz)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.limpar_vitrine_eventos_expirados(timestamptz)
  TO service_role;

COMMENT ON TABLE public.vitrine_links IS
  'Links temporários de shortlist. token_hash é SHA-256; o token bruto nunca é persistido.';
COMMENT ON TABLE public.vitrine_link_eventos IS
  'Sinais públicos sem PII, ligados ao lead apenas por vitrine_links no domínio interno.';
